table 'Codici colore'
	lineageTag: cdbcf8e2-ebe5-411e-a625-0a143a682e81

	column 'Codice Colore'
		dataType: string
		lineageTag: e98072b5-3753-4cea-9711-6cebb5214cce
		summarizeBy: none
		sourceColumn: Codice Colore

		annotation SummarizationSetBy = Automatic

	column Colore
		dataType: string
		lineageTag: 0d27fa23-5588-4ff9-8ae5-bc9113a8f7fb
		summarizeBy: none
		sourceColumn: Colore

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		lineageTag: cbe6e5ca-a2fd-4c67-bffe-7f428afba0e4
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column 'Codice colore per BI'
		dataType: string
		lineageTag: 1834f160-d148-4a67-9152-f1804ccddc96
		summarizeBy: none
		sourceColumn: Codice colore per BI

		annotation SummarizationSetBy = Automatic

	partition 'Codici colore' = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\gessica.dilenardo\Documents\Power BI\Dati\Codici colore.xlsx"), null, true),
				    #"Codici colore_Sheet" = Origine{[Item="Codici colore",Kind="Sheet"]}[Data],
				    #"Intestazioni alzate di livello" = Table.PromoteHeaders(#"Codici colore_Sheet", [PromoteAllScalars=true]),
				    #"Modificato tipo" = Table.TransformColumnTypes(#"Intestazioni alzate di livello",{{"Codice Colore", type text}, {"Colore", type text}})
				in
				    #"Modificato tipo"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

