table Indice_versioni
	isHidden
	lineageTag: e954b684-ef8a-4c6f-b724-93e5b57e55bc

	measure 'Versione corrente' = ```
			
			VAR UltimaModifica = MAX(Indice_versioni[Data inizio modifiche])
			VAR UltimoRilascio = MAX(Indice_versioni[Data rilascio])
			VAR VersioneModifica = MAXX(
			    FILTER(Indice_versioni, Indice_versioni[Data inizio modifiche] = UltimaModifica), 
			    Indice_versioni[n째 versione]
			)
			VAR VersioneRilascio = MAXX(
			    FILTER(Indice_versioni, Indice_versioni[Data rilascio] = UltimoRilascio), 
			    Indice_versioni[n째 versione]
			)
			RETURN
			IF(
			    (UltimaModifica > UltimoRilascio || ISBLANK(UltimoRilascio)),
			    VersioneModifica & ".dev",
			    VersioneRilascio
			)
			```
		lineageTag: 5784d27b-3e71-4ac6-a070-fc4656d04c29

	column 'n째 versione'
		dataType: string
		isHidden
		lineageTag: b1dd933e-c238-44cb-b114-26fa7a4eb9f3
		summarizeBy: none
		sourceColumn: n째 versione

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modifiche
		dataType: string
		isHidden
		lineageTag: c1f4cc91-583e-45ac-bf5e-c372ce779a29
		summarizeBy: none
		sourceColumn: Modifiche

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data inizio modifiche'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 9076efa1-27b2-4905-95ec-78cf8f5693bc
		summarizeBy: none
		sourceColumn: Data inizio modifiche

		variation Variazione
			isDefault
			relationship: 569ad2e5-60e1-49dc-aa73-e0e2e0d30ef6
			defaultHierarchy: LocalDateTable_c09d6255-1ee2-4840-9d06-bb52ea5ef7c1.'Gerarchia data'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data rilascio'
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: a1f77adc-d1d6-4be1-9c70-fa5454eac97d
		summarizeBy: none
		sourceColumn: Data rilascio

		variation Variazione
			isDefault
			relationship: 8ea8ab2a-ba5e-476f-8c84-3b34923b95f8
			defaultHierarchy: LocalDateTable_7fa43507-739e-44b0-853e-051210971438.'Gerarchia data'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Indice_versioni = m
		mode: import
		source =
				let
				    Origine = Excel.Workbook(File.Contents("C:\Users\gessica.dilenardo\Documents\Power BI\Elaborati\BI_Magazzino_Anagrafica_Articoli\Versionamento\Indice versioni.xlsx"), null, true),
				    Indice_versioni_Table = Origine{[Item="Indice_versioni",Kind="Table"]}[Data],
				    #"Modificato tipo" = Table.TransformColumnTypes(Indice_versioni_Table,{{"Data inizio modifiche", type date}, {"Data rilascio", type date}})
				in
				    #"Modificato tipo"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

