table 'Listini vendita (liav)'
	lineageTag: 4d390e82-a0ae-4ef6-9c64-3d00393a35ea

	column Prezzo
		dataType: double
		lineageTag: 2c7e271b-5d24-4264-8efd-8bf377847e63
		summarizeBy: sum
		sourceColumn: Prezzo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data entrata in vigore'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c9bf66e0-e675-47d3-98ff-0f671d74255d
		summarizeBy: none
		sourceColumn: Data entrata in vigore

		variation Variazione
			isDefault
			relationship: a11e2c7c-eb5d-461a-8a10-3ff48be8757c
			defaultHierarchy: LocalDateTable_b72a4a6c-3bc0-493a-856c-7d1c89c961d7.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Codice Articolo'
		dataType: string
		lineageTag: c5296a2c-d966-40e1-9e6b-2f18c24403b3
		summarizeBy: none
		sourceColumn: Codice Articolo

		annotation SummarizationSetBy = Automatic

	column Sconto
		dataType: string
		lineageTag: 43955acd-d6c6-4e2d-bef1-02698eca09bd
		summarizeBy: none
		sourceColumn: Sconto

		annotation SummarizationSetBy = Automatic

	column 'Data fine vigore'
		dataType: dateTime
		formatString: Long Date
		lineageTag: da1d3ec2-f670-456b-a932-465ff22db8a7
		summarizeBy: none
		sourceColumn: Data fine vigore

		variation Variazione
			isDefault
			relationship: b59513c3-83e7-4ca7-b494-12852803ac2c
			defaultHierarchy: LocalDateTable_c18939e1-0c17-4cb6-aef4-e7817106196a.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Operatore
		dataType: string
		lineageTag: 4ee97818-5083-4b21-a9ad-f699a7b45a9f
		summarizeBy: none
		sourceColumn: Operatore

		annotation SummarizationSetBy = Automatic

	column 'Data modifica'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0ff966a-10de-4b02-965f-3bd867df3bc6
		summarizeBy: none
		sourceColumn: Data modifica

		variation Variazione
			isDefault
			relationship: ebc14423-3b78-4ee9-97eb-ea892251a3fa
			defaultHierarchy: LocalDateTable_e4cc534b-9cf0-4dad-9972-1e2ef5b7d0e8.'Gerarchia data'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Listini vendita (liav)' = m
		mode: import
		source =
				let
				    Origine = Odbc.Query("dsn=F12 Informix DB", "select * from liav"),
				    #"Rinominate colonne" = Table.RenameColumns(Origine,{{"lia_prezzo", "Prezzo"}, {"lia_data_ent_vig", "Data entrata in vigore"}, {"lia_sigla_art", "Codice Articolo"}, {"lia_operatore", "Operatore"}, {"lia_sconto", "Sconto"}, {"lia_data_fin_vig", "Data fine vigore"}, {"lia_data_variaz", "Data modifica"}}),
				    #"Rimosse altre colonne" = Table.SelectColumns(#"Rinominate colonne",{"Prezzo", "Data entrata in vigore", "Codice Articolo", "Sconto", "Data fine vigore", "Operatore", "Data modifica"})
				in
				    #"Rimosse altre colonne"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

