table 'Movimenti articoli (mmov)'
	lineageTag: 47e71906-a17d-447a-ab52-676498a7db1c

	measure 'Quantità articoli movimentati' = SUM('Movimenti articoli (mmov)'[Quantità])
		formatString: 0
		lineageTag: e6651501-e74c-4053-afd3-c9c74e7d8699

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Codici movimentati' = DISTINCTCOUNT('Movimenti articoli (mmov)'[Codice articolo])
		formatString: 0
		lineageTag: 26ba96f7-6862-444d-b4ff-4ff4cb9e7662

	column Quantità
		dataType: double
		lineageTag: ca991b99-1b32-4959-8f3d-b016043675f5
		summarizeBy: sum
		sourceColumn: Quantità

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column codice_fornitore
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 35f65068-ee49-44ed-b789-1514230e1df2
		summarizeBy: sum
		sourceColumn: codice_fornitore

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data movimento'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b4b3f18c-167a-43b9-8761-4e2c946e6c2a
		summarizeBy: none
		sourceColumn: Data movimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column causale_movimento
		dataType: string
		isHidden
		lineageTag: bb82b364-07c2-41a3-aa82-e84df2843280
		summarizeBy: none
		sourceColumn: causale_movimento

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Codice articolo'
		dataType: string
		lineageTag: 3572937c-0eb7-4999-85ed-ecf8fcfd0fd2
		summarizeBy: none
		sourceColumn: Codice articolo

		annotation SummarizationSetBy = Automatic

	column Deposito
		dataType: string
		lineageTag: 9472da02-86fd-4abc-ba8f-b21417eb6742
		summarizeBy: none
		sourceColumn: Deposito

		annotation SummarizationSetBy = Automatic

	column 'Codice fornitore' =
			
			VAR NumeroOrigine = 'Movimenti articoli (mmov)'[codice_fornitore]
			VAR Mastro = QUOTIENT(NumeroOrigine,10000000)
			VAR x = NumeroOrigine - (Mastro*10000000)
			VAR Conto = QUOTIENT(x,10000)
			VAR Sottoconto = x-(Conto*10000)
			RETURN Mastro & "-" & Conto & "-" & Sottoconto
		lineageTag: e28d0587-ea27-48be-bcc8-663024ea647a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Causale movimento' = RELATED('Causali movimento (mcau)'[Descrizione causale movimento])
		lineageTag: 2749bf78-c2e9-489f-b9aa-778df2bb01a2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Descrizione deposito' = LOOKUPVALUE('Depositi (dep)'[Descrizione deposito],'Depositi (dep)'[sigla_deposito],'Movimenti articoli (mmov)'[Deposito])
		lineageTag: accab23d-eb23-4d6e-8859-bb8e1f567836
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Movimenti articoli (mmov)' = m
		mode: import
		source =
				let
				    Origine = Odbc.Query("dsn=F12 Informix DB", "select*from mmov"),
				    #"Rinominate colonne" = Table.RenameColumns(Origine,{{"m_qta", "Quantità"}, {"m_cod_for", "codice_fornitore"}, {"m_data_mov", "Data movimento"}, {"m_caus_mov", "causale_movimento"}, {"m_sig_art", "Codice articolo"}, {"m_dep", "Deposito"}}),
				    #"Rimosse altre colonne" = Table.SelectColumns(#"Rinominate colonne",{"Quantità", "codice_fornitore", "Data movimento", "causale_movimento", "Codice articolo", "Deposito"})
				in
				    #"Rimosse altre colonne"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

