table MRP
	isHidden
	lineageTag: b9ecad0a-f2f7-4ed2-a871-eff48f1d0609

	column tipo_mrp*
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1eb1fd9d-a7f8-4ce5-99bd-66baeaa8413c
		summarizeBy: sum
		sourceColumn: tipo_mrp*

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tipo di MRP'
		dataType: string
		isHidden
		lineageTag: 07ee5f57-1f78-43f8-853b-1e20b24f77e2
		summarizeBy: none
		sourceColumn: Tipo di MRP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition MRP = m
		mode: import
		source =
				let
				    Origine = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQpOzi8qSVTIzCtJLS5JBLIScxSSczJTgXylWJ1oJSOgGt+AYDDbBMQOClBILC3Jz00syUzOB+pTSC3LTEnNq0oEKzGFKvFNzCtNzIEYYYahDSxsARQOclRw1vdRio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"tipo_mrp*" = _t, #"Tipo di MRP" = _t]),
				    #"Modificato tipo" = Table.TransformColumnTypes(Origine,{{"tipo_mrp*", Int64.Type}, {"Tipo di MRP", type text}})
				in
				    #"Modificato tipo"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigazione

