table 'Ordini acquisto'
	lineageTag: 78d29009-61b6-444c-8af0-b85d518a4902

	measure 'Codici acquistati' = DISTINCTCOUNT('Ordini acquisto'[Codice articolo])
		formatString: 0
		lineageTag: b375c0ed-6897-461c-ac5f-f856f268cc90

	measure 'Quantità articoli ordinati' = SUM('Ordini acquisto'[Quantità ordinata])
		formatString: 0
		lineageTag: fa7914c4-8c20-4298-9f57-f546740ce355

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Quantità ordinata'
		dataType: double
		isHidden
		lineageTag: 89433fad-dbeb-40e9-815d-90bcebaccb63
		summarizeBy: sum
		sourceColumn: Quantità ordinata

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column numero_ordine
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 66252fc3-8a08-453a-b491-295a230276c9
		summarizeBy: none
		sourceColumn: numero_ordine

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Riga ordine'
		dataType: int64
		formatString: 0
		lineageTag: 089b1721-2e3a-41db-871b-498525095ac9
		summarizeBy: sum
		sourceColumn: Riga ordine

		annotation SummarizationSetBy = Automatic

	column 'Codice articolo'
		dataType: string
		lineageTag: 06473159-7a98-406a-b3b3-99527497cbd9
		summarizeBy: none
		sourceColumn: Codice articolo

		annotation SummarizationSetBy = Automatic

	column codice_fornitore = RELATED('Testata ordini acquisto (ofi)'[codice_fornitore])
		isHidden
		formatString: 0
		lineageTag: 9ef84bbe-3858-4b59-84c9-880cb84e804a
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Data ordine' = RELATED('Testata ordini acquisto (ofi)'[Data ordine])
		formatString: Short Date
		lineageTag: 9fa7803a-787f-4bc4-83b4-8e70bacd09a8
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Codice fornitore' =
			
			VAR NumeroOrigine = 'Ordini acquisto'[codice_fornitore]
			VAR Mastro = QUOTIENT(NumeroOrigine,10000000)
			VAR x = NumeroOrigine - (Mastro*10000000)
			VAR Conto = QUOTIENT(x,10000)
			VAR Sottoconto = x-(Conto*10000)
			RETURN Mastro & "-" & Conto & "-" & Sottoconto
		lineageTag: 5a3855c2-6fb8-4cf4-8026-2f4d822d4a01
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Numero Ordine' =
			
			VAR NumeroOriginale = 'Ordini acquisto'[numero_ordine] -- Il numero originale
			VAR LunghezzaPrefisso = 2 -- Il numero di cifre fisse del prefisso
			VAR Prefisso = (LEFT(NumeroOriginale, LunghezzaPrefisso))-10 -- Estrae il prefisso
			VAR Suffisso = MOD(NumeroOriginale,10000000) -- Estrae il suffisso variabile
			RETURN Prefisso & "/" & Suffisso
		lineageTag: c3ae87d2-56ab-4b1a-8518-5cee05216e4c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Descrizione fornitore' = LOOKUPVALUE('S/Conto'[Descrizione fornitore/cliente],'S/Conto'[codice_s_conto],'Ordini acquisto'[codice_fornitore])
		lineageTag: 9e4b67ac-a0ee-4cbc-adc7-d8b0ca085e6e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Ordini acquisto' = m
		mode: import
		source =
				let
				    Origine = Odbc.Query("dsn=F12 Informix DB", "select*from ofr"),
				    #"Rinominate colonne" = Table.RenameColumns(Origine,{{"oq_qta_ordinata", "Quantità ordinata"}, {"oq_ser_ord", "numero_ordine"}, {"oq_sigla_art", "Codice articolo"}, {"oq_num_r_ord", "Riga ordine"}}),
				    #"Rimosse altre colonne" = Table.SelectColumns(#"Rinominate colonne",{"Quantità ordinata", "numero_ordine", "Riga ordine", "Codice articolo"})
				in
				    #"Rimosse altre colonne"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

