table 'Qualifica Articolo'
	isHidden
	lineageTag: 72d19b0b-cc0c-4219-b64d-c359ae5d0ddd

	column qualifica+
		dataType: string
		lineageTag: 1ab21cb6-b7c1-4041-b5f9-bf6f835473f5
		summarizeBy: none
		sourceColumn: qualifica+

		annotation SummarizationSetBy = Automatic

	column 'Qualifica Articolo'
		dataType: string
		lineageTag: 9685cfb4-339a-42c8-891f-bbeb229c6154
		summarizeBy: none
		sourceColumn: Qualifica Articolo

		annotation SummarizationSetBy = Automatic

	partition 'Qualifica Articolo' = m
		mode: import
		source =
				let
				    Origine = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Pc3BCoMwDIDhVyk5+xLiEDwIQ4/FQ9bmELBNid0OffpFHTvmyx/iPfTQQR8CHYcoC2ydh8FowFRYMl0wGjxVotQqbuTM9Q4n8ylX0kSRxUV2Z/Vu/8PZghktYLQVJ7x0MV04YHr9Hj7OTCLt+z2vNq/yUSxFqTXD7Qs=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"qualifica+" = _t, #"Qualifica Articolo" = _t])
				in
				    Origine

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigazione

