table S/Conto
	lineageTag: d2884aef-aa97-4cb9-b575-4aa7ab16ee2a

	column codice_s_conto
		dataType: int64
		formatString: 0
		lineageTag: 341edebf-300c-472b-88fb-e9dba8d4694b
		summarizeBy: none
		sourceColumn: codice_s_conto

		annotation SummarizationSetBy = User

	column 'Descrizione fornitore/cliente'
		dataType: string
		lineageTag: 9e1d26f2-40a3-4431-9d58-2d8aa403a152
		summarizeBy: none
		sourceColumn: Descrizione fornitore/cliente

		annotation SummarizationSetBy = Automatic

	column 'Codice S/conto' =
			
			VAR NumeroOrigine = 'S/Conto'[codice_s_conto]
			VAR Mastro = QUOTIENT(NumeroOrigine,10000000)
			VAR x = NumeroOrigine - (Mastro*10000000)
			VAR Conto = QUOTIENT(x,10000)
			VAR Sottoconto = x-(Conto*10000)
			RETURN Mastro & "-" & Conto & "-" & Sottoconto
		lineageTag: bc3cfbf9-df16-4ce9-9809-3f06299d0b35
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition S/Conto = m
		mode: import
		source =
				let
				    Origine = Odbc.Query("dsn=F12 Informix DB", "select * from sco"),
				    #"Rinominate colonne" = Table.RenameColumns(Origine,{{"sc_cod_s_conto", "codice_s_conto"}, {"sc_descr", "Descrizione fornitore/cliente"}}),
				    #"Rimosse altre colonne" = Table.SelectColumns(#"Rinominate colonne",{"codice_s_conto", "Descrizione fornitore/cliente"})
				in
				    #"Rimosse altre colonne"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

